using QC = Microsoft.Data.SqlClient;
using DT = System.Data;

using FineWoodworkingBasic.Util;


namespace FineWoodworkingBasic.Model
{
    public class AuthorizedUser : Persistable
    {
        protected int? ID { get; set; }
        protected string userName { get; set; }
        protected string password { get; set; }

        public AuthorizedUser()
        {
            ID = 0;
            userName = " ";
            password = "0";
        }

        public AuthorizedUser(string usName, string pwd)
        {

            userName = usName;
            password = Utilities.Encrypt(pwd);
        }

        public void SetValues(string nm, string pwd)
        {
            userName = nm;
            password = Utilities.Encrypt(pwd);
        }

        public void SetPasswordWithEncryptedValue(string encryptedPwd)
        {
            password = encryptedPwd;
        }

        public void SetPasswordWithPlainText(string plainTextPwd)
        { 
            password = Utilities.Encrypt(plainTextPwd); 
        }


        public bool CheckIfPasswordsMatch(string providedPassword)
        {
            string encryptedProvidedPassword = Utilities.Encrypt(providedPassword);
            if (string.Equals(encryptedProvidedPassword, password))
            {
                return true;
            }
            return false;
        }

        public virtual void Populate(string userNameToUse)
        {
            
            Dictionary<string, Object> dict = new Dictionary<string, Object>();
            dict["Username"] = userNameToUse;
            PopulateHelper(dict);
        }

        protected override void ConstructPopulateQueryCommand(Dictionary<string, Object> dictIdToUse, QC.SqlCommand command)
        {
            QC.SqlParameter parameter;

            string query = @"SELECT * FROM AuthorizedUser WHERE (Username = @UN);";

            //string query = @"SELECT * FROM AuthorizedUser WHERE (Username = '" + dictIdToUse["Username"] + "');";

            command.CommandText = query;

            parameter = new QC.SqlParameter("@UN", DT.SqlDbType.NVarChar, 50);
            parameter.Value = dictIdToUse["Username"];
            command.Parameters.Add(parameter);

           // DEBUG Console.WriteLine(command.CommandText);

        }

        protected override void ProcessPopulateQueryResult(QC.SqlDataReader reader)
        {
            while (reader.Read())
            {
                ID = reader.GetInt32(0);
                userName = reader.GetString(1);
                password = reader.GetString(2);
            }
        }

        public override bool IsPopulated()
        {
            if (this.ID == null) return false;
            if (this.ID == 0) return false;
            return true;
        }

        protected override void SetupCommandForInsert(QC.SqlCommand command)
        {

            QC.SqlParameter parameter;

            string insertQuery = "INSERT INTO AuthorizedUser (Username, Password) " +
                " OUTPUT INSERTED.ID " +
                " VALUES (@Username, @Password);";

            command.CommandText = insertQuery;

            parameter = new QC.SqlParameter("@Username", DT.SqlDbType.NVarChar, 100);  // Fix Type and Length 
            parameter.Value = this.userName;
            command.Parameters.Add(parameter);

            parameter = new QC.SqlParameter("@Password", DT.SqlDbType.NVarChar, 100); // Fix Type and Length  
            parameter.Value = this.password;
            command.Parameters.Add(parameter);

        }

        protected override void SetAutogeneratedIDFromInsert(int genID)
        {
            this.ID = genID;
        }

        protected override void SetupCommandForUpdate(QC.SqlCommand command)
        {
            QC.SqlParameter parameter;

            string updateQuery = "UPDATE AuthorizedUser" +
               " SET Username = @Username, Password = @Password " +
               " WHERE (ID = @ID);";

            command.CommandText = updateQuery;

            parameter = new QC.SqlParameter("@Username", DT.SqlDbType.NVarChar, 100);  // Fix Type and Length 
            parameter.Value = this.userName;
            command.Parameters.Add(parameter);

            parameter = new QC.SqlParameter("@Password", DT.SqlDbType.NVarChar, 100); // Fix Type and Length  
            parameter.Value = this.password;
            command.Parameters.Add(parameter);

            parameter = new QC.SqlParameter("@ID", DT.SqlDbType.Int);  // Fix Type and Length 
            parameter.Value = this.ID;
            command.Parameters.Add(parameter);


        }
        protected override bool IsNewObject()
        {
            if (ID == null)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        protected override ResultMessage GetResultMessageForSave()
        {
            ResultMessage mesg = new ResultMessage(ResultMessage.ResultMessageType.Success, "User with name: " + this.userName
                    + " saved successfully into database!");
            return mesg;
        }

        protected override ResultMessage GetErrorMessageForSave(Exception Ex)
        {
            ResultMessage mesg = new ResultMessage(ResultMessage.ResultMessageType.Error, "Error in saving User with Name: " + this.userName +
                " into database!" + Ex.ToString());
            return mesg;
        }

        public override string ToString()
        {
            return "ID: " + ID + "; Username: " + userName + "; Password (encrypted): " + password;
        }

        protected override ResultMessage GetErrorMessageForPopulate(Exception Ex)
        {
            ResultMessage mesg = new ResultMessage(ResultMessage.ResultMessageType.Error, "ERROR: Error in retrieving User with ID: " + this.ID +
                " from database!");
            return mesg;
        }

        protected override ResultMessage GetResultMessageForPopulate()
        {
            ResultMessage mesg;
            if ((this.ID == null) || (this.ID == 0))
                mesg = new ResultMessage(ResultMessage.ResultMessageType.Error, "ERROR: No user found!");
            else
             mesg = new ResultMessage(ResultMessage.ResultMessageType.Success, "Authorized User with ID: " + this.ID +
                " retrieved successfully!");
            return mesg;
        }
    }



}

