using System.Globalization;
using DT = System.Data;
using QC = Microsoft.Data.SqlClient;
using FineWoodworkingBasic.Util;
using System.Security.Cryptography.X509Certificates;
using System.Data.SqlTypes;

namespace FineWoodworkingBasic.Model
{

    public class LocationConstraint : Persistable
    {

        public SqlGuid ID { get; protected set; } = new SqlGuid();
        public string Description { get; protected set; } = "";

        public LocationConstraint(SqlGuid Id, string desc)
        {
            ID = Id;
            Description = desc;
        }

        public LocationConstraint(string desc)
        {
            Description = desc;
        }

        public void Populate(SqlGuid idToUse)
        {
            Dictionary<string, Object> d = new Dictionary<string, Object>();
            d["id"] = idToUse;
            PopulateHelper(d);
        }

        protected override void ConstructPopulateQueryCommand(Dictionary<string,Object>  dictIdToUse, QC.SqlCommand command)
        {
            QC.SqlParameter parameter;

            string query = @"SELECT * FROM LocationConstraint WHERE (ID = @Id);";

            command.CommandText = query;

            parameter = new QC.SqlParameter("@Id", DT.SqlDbType.UniqueIdentifier);
            parameter.Value = dictIdToUse["id"];
            command.Parameters.Add(parameter);

        }

        protected override void ProcessPopulateQueryResult( QC.SqlDataReader reader)
        {
            while (reader.Read())
            {
                ID = reader.GetSqlGuid(reader.GetOrdinal("ID"));
                Description = reader.GetString(reader.GetOrdinal("Description"));
            }
        }

        public override bool IsPopulated()
        {
            if (this.ID.IsNull) return false;
            return true;
        }

        protected override void SetupCommandForInsert(QC.SqlCommand command)
        {
            // Taking a 'PreparedStatement' approach here, avoids SQL Injection  
            // THIS IS IMPORTANT 

            QC.SqlParameter parameter;

            string insertQuery = "INSERT INTO LocationConstraint (Description) " +
                " OUTPUT INSERTED.ID " +
                " VALUES (@Description);";

            command.CommandText = insertQuery;

            parameter = new QC.SqlParameter("@Description", DT.SqlDbType.NVarChar, 2000);  // Fix Type and Length 
            parameter.Value = Description;
            command.Parameters.Add(parameter);
        }

        protected override void SetAutogeneratedIDFromInsert(SqlGuid genID)
        {
            this.ID = genID;
        }

        protected override void SetupCommandForUpdate(QC.SqlCommand command)
        {
            QC.SqlParameter parameter;

            string updateQuery = "UPDATE LocationConstraint" +
               " SET Description = @Description " +
               " WHERE (ID = @Id);";

            command.CommandText = updateQuery;

            parameter = new QC.SqlParameter("@Description", DT.SqlDbType.NVarChar, 2000);  // Fix Type and Length 
            parameter.Value = Description;
            command.Parameters.Add(parameter);

            parameter = new QC.SqlParameter("@Id", DT.SqlDbType.UniqueIdentifier);  // Fix Type and Length 
            parameter.Value = ID;
            command.Parameters.Add(parameter);
        }

        protected override bool IsNewObject()
        {
            return !this.IsPopulated();
        }

        protected override ResultMessage GetResultMessageForPopulate()
        {
            ResultMessage mesg = new ResultMessage(ResultMessage.ResultMessageType.Success, "LocationConstraint retrieved successfully!");
            return mesg;
        }

        protected override ResultMessage GetResultMessageForSave()
        {
            ResultMessage mesg = new ResultMessage(ResultMessage.ResultMessageType.Success, "LocationConstraint saved successfully into database!");
            return mesg;
        }

        protected override ResultMessage GetErrorMessageForPopulate(Exception Ex)
        {
            ResultMessage mesg = new ResultMessage(ResultMessage.ResultMessageType.Error, "Error in retrieving LocationConstraint from database!");
            return mesg;
        }

        protected override ResultMessage GetErrorMessageForSave(Exception Ex)
        {
            ResultMessage mesg = new ResultMessage(ResultMessage.ResultMessageType.Error, "Error in saving LocationConstraint into database!");
            return mesg;
        }

        public override bool Equals(object? obj)
        {
            if (obj == null) return false;
            if (this.GetType() != obj.GetType()) return false;

            LocationConstraint other = (LocationConstraint)obj;

            if (!this.ID.Equals(other.ID)) return false;

            if (!this.Description.Equals(other.Description)) return false;

            return true;
        }

        public override int GetHashCode()
        {
            throw new NotImplementedException();
        }

        public override string ToString()
        {
            return "\nLocationConstraint\n----------\n" +
            $"   Description: {Description}";
        }

    }

}