using System.Globalization;
using DT = System.Data;
using QC = Microsoft.Data.SqlClient;
using FineWoodworkingBasic.Util;
using System.Security.Cryptography.X509Certificates;
using System.Data.SqlTypes;

namespace FineWoodworkingBasic.Model
{

    public class LocationConstraint : Persistable
    {

        protected SqlGuid? ID { get; set; }
        protected string Description { get; set; }

        public LocationConstraint()
        {
            ID = new SqlGuid();
            Description = "";
        }

        public LocationConstraint(SqlGuid Id, string desc)
        {
            ID = Id;
            Description = desc;
        }

        public LocationConstraint(string desc)
        {
            Description = desc;
        }

        public void Populate(SqlGuid idToUse)
        {
            string IDStr = idToUse + "";
            Dictionary<string, Object> d = new Dictionary<string, Object>();
            d["id"] = IDStr;
            PopulateHelper(d);
        }

        protected override void ConstructPopulateQueryCommand(Dictionary<string,Object>  dictIdToUse, QC.SqlCommand command)
        {
            QC.SqlParameter parameter;

            string query = @"SELECT * FROM LocationConstraint WHERE (ID = @NP);";

            command.CommandText = query;

            parameter = new QC.SqlParameter("@NP", DT.SqlDbType.UniqueIdentifier);
            parameter.Value = dictIdToUse["id"];
            command.Parameters.Add(parameter);

        }

        protected override void ProcessPopulateQueryResult( QC.SqlDataReader reader)
        {
            while (reader.Read())
            {
                ID = reader.GetSqlGuid(0);
                Description = reader.GetString(1);
            }
        }

        public override bool IsPopulated()
        {
            if (this.ID == null) return false;
            if (this.ID.Equals(0)) return false;
            return true;
        }

        protected override void SetupCommandForInsert(QC.SqlCommand command)
        {
            // Taking a 'PreparedStatement' approach here, avoids SQL Injection  
            // THIS IS IMPORTANT 

            QC.SqlParameter parameter;

            string insertQuery = "INSERT INTO LocationConstraint (Description) " +
                " OUTPUT INSERTED.ID " +
                " VALUES (@Description);";

            command.CommandText = insertQuery;

            parameter = new QC.SqlParameter("@Description", DT.SqlDbType.NVarChar, 2000);  // Fix Type and Length 
            parameter.Value = Description;
            command.Parameters.Add(parameter);
        }

        protected override void SetAutogeneratedIDFromInsert(SqlGuid genID)
        {
            this.ID = genID;
        }

        protected override void SetupCommandForUpdate(QC.SqlCommand command)
        {
            QC.SqlParameter parameter;

            string updateQuery = "UPDATE LocationConstraint" +
               " SET Description = @Description " +
               " WHERE (ID = @Id);";

            command.CommandText = updateQuery;

            parameter = new QC.SqlParameter("@Description", DT.SqlDbType.NVarChar, 2000);  // Fix Type and Length 
            parameter.Value = Description;
            command.Parameters.Add(parameter);

            parameter = new QC.SqlParameter("@Id", DT.SqlDbType.UniqueIdentifier);  // Fix Type and Length 
            parameter.Value = ID;
            command.Parameters.Add(parameter);
        }

        protected override bool IsNewObject()
        {
            if (ID == null)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        protected override ResultMessage GetResultMessageForPopulate()
        {
            ResultMessage mesg = new ResultMessage(ResultMessage.ResultMessageType.Success, "LocationConstraint with ID: " + this.ID + 
                " retrieved successfully!");
            return mesg;
        }

        protected override ResultMessage GetResultMessageForSave()
        {
            ResultMessage mesg = new ResultMessage(ResultMessage.ResultMessageType.Success, "LocationConstraint with ID: " + this.ID
                + " saved successfully into database!");
            return mesg;
        }

        protected override ResultMessage GetErrorMessageForPopulate(Exception Ex)
        {
            ResultMessage mesg = new ResultMessage(ResultMessage.ResultMessageType.Error, "Error in retrieving LocationConstraint with ID: " + this.ID +
                " from database!");
            return mesg;
        }

        protected override ResultMessage GetErrorMessageForSave(Exception Ex)
        {
            ResultMessage mesg = new ResultMessage(ResultMessage.ResultMessageType.Error, "Error in saving LocationConstraint with ID: " + this.ID
                + " into database!");
            return mesg;
        }

        public override string ToString()
        {
            return "ID: " + ID + "; Description: " + Description + " ";
        }

    }

}