using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using QC = Microsoft.Data.SqlClient;

namespace FineWoodworkingBasic.Model
{
    public abstract class PersistableCollection : Persistable
    {

        public override void Save() {}

        protected override bool IsNewObject()
        { return false; }

        public override bool IsPopulated()
        { return true; }

        protected override void SetupCommandForInsert(QC.SqlCommand command) { }

        protected override void SetupCommandForUpdate(QC.SqlCommand command) { }

        protected override void SetAutogeneratedIDFromInsert(SqlGuid genID) { }


     
    }
}
